---
title: "DE"
author: "Wendy Zhang"
date: "2023-12-03"
output: html_document
---
```{r}
countData=read.csv("RNAseq_LUSC.csv")
```


```{r}
library(stringr)
# Assuming RNA_data is your data frame
colnames(countData) <- str_sub(str_replace_all(colnames(countData), "\\.", "-"), 1, 12)
```

```{r}
colData<-cluster
rownames(colData)<-str_sub(row.names(colData),1,12)
head(colData)
```

```{r}
# Assuming countData is your data frame
rownames(countData) <- countData[, 1]

# Remove the first column from countData
countData <- countData[, -1]

countData <- countData[rowSums(countData)>1,]

head(countData)

```

```{r}
# Extract common column names
common_cols <- intersect(colnames(countData), rownames(colData))
common_cols<- intersect(common_cols,unique_pat)

# Subset countData to keep only common columns
countData<- countData[, common_cols]

# Display the filtered countData
head(countData)

```
```{r}
# Assuming desired_order is already defined
desired_order <- colnames(countData)

# Reorder rows in colData based on desired_order
colData <- colData[desired_order, , drop = FALSE]

colData
```



```{r}
library(DESeq2)
```

```{r}
# Get the cluster assignments for the common samples
cluster_labels <-colData$`cutree(res$tree_col, k = 2)`

# Add cluster_labels to colData
colData$cluster_group <- factor(cluster_labels)

head(colData)
```
```{r}

head(colData)
head(countData)
```
```{r}
colData<-colData[,-1]
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~ cluster_group)

dds
```
```{r}
dds = DESeq(dds)
res <- results(dds)
res
```
```{r}
summary(res)
```

#The stuff with alpha idk
```{r}
res.05 <- results(dds, alpha = 0.05)
table(res.05$padj < 0.05)
```
```{r}
resLFC1 <- results(dds, lfcThreshold=1)
table(resLFC1$padj < 0.1)
```
```{r}
res <- res[order(res$pvalue),]
summary(res)
```
```{r}
sum(res$padj < 0.06, na.rm=TRUE)
```
```{r}
head(resSig[ order( resSig$log2FoldChange, decreasing=TRUE), ])
```

```{r}
res = results(dds, contrast=c("cluster_group", "1", "2"))
```


```{r}
gene_symbols <- rownames(countData)
gene_symbols_mutations <- data_mutation_common$Hugo_Symbol

cluster_labels <-cluster$`cutree(res$tree_col, k = 2)`
enrich_result_cluster <- enrichPathway(gene = cluster_labels, organism = "human")

# Visualize enrichment results
dotplot(enrich_result_cluster)

```


```{r}
plotMA(res, ylim=c(-2,2))
```
```{r}
plotCounts(dds, gene=which.min(res$padj), intgroup="cluster_group")
```

```{r}
library("AnnotationDbi")
library("org.Hs.eg.db")
```

```{r}
columns(org.Hs.eg.db)
```

```{r}
# the Ensembl gene ID "ENSG00000000003.15"
#Gene ID: ENSG00000000003, Version: 15
# Remove version from Ensembl gene IDs in row names
rownames(res) <- sub("\\.\\d+$", "", rownames(res))

res$symbol = mapIds(org.Hs.eg.db,
                    keys=row.names(res), 
                    column="SYMBOL",
                    keytype="ENSEMBL",
                    multiVals="first")
```

```{r}
# Assuming your Ensembl gene IDs are stored in a vector like this:
ensembl_ids <- c("ENSG00000121410", "ENSG00000175899", "ENSG00000291190")

# Map Ensembl IDs to gene symbols
gene_symbols <- mapIds(org.Hs.eg.db,
                       keys = ensembl_ids,
                       column = "SYMBOL",
                       keytype = "ENSEMBL",
                       multiVals = "first")

# Print the result
print(gene_symbols)

```


```{r}
res$entrez = mapIds(org.Hs.eg.db,
                    keys=row.names(res), 
                    column="ENTREZID",
                    keytype="ENSEMBL",
                    multiVals="first")
```
```{r}
res$name =   mapIds(org.Hs.eg.db,
                    keys=row.names(res), 
                    column="GENENAME",
                    keytype="ENSEMBL",
                    multiVals="first")
```

```{r}
head(res, 10)
```


```{r}
library(pathview)
library(gage)
```
```{r}
library(gageData)

data(kegg.sets.hs)
data(sigmet.idx.hs)

# Focus on signaling and metabolic pathways only
kegg.sets.hs = kegg.sets.hs[sigmet.idx.hs]

# Examine the first 3 pathways
head(kegg.sets.hs, 3)
```
```{r}
foldchanges = res$log2FoldChange
names(foldchanges) = res$entrez
head(foldchanges)
```
```{r}
library(gage)
# Get the results
keggres = gage(foldchanges, gsets=kegg.sets.hs)
```

```{r}
attributes(keggres)
```


```{r}
# Look at the first few down (less) pathways
head(keggres$less)
```

```{r}
pathview(gene.data=foldchanges, pathway.id="hsa04110")
```
```{r}
## Focus on top 5 upregulated pathways here for demo purposes only
keggrespathways <- rownames(keggres$greater)[1:5]

# Extract the 8 character long IDs part of each string
keggresids = substr(keggrespathways, start=1, stop=8)
keggresids
```
```{r}
# pathview(gene.data=foldchanges, pathway.id=keggresids, species="hsa")
```




