---
title: "project"
author: "Wendy Zhang"
date: "2023-11-23"
output: html_document
---

```{r}
#Plotting Distributions

RNA_data <- read.csv("/Users/ameliemarshall/Desktop/RNAseq_LUSC.csv")
data_clinical_patient <- read.csv("/Users/ameliemarshall/Desktop/data_clinical_patient.txt", sep = '\t', header = TRUE, skip = 4)
#ski first 4 data that not relates to patient ID
data_mutations <- read.csv("/Users/ameliemarshall/Desktop/data_mutations.txt", sep = '\t', header = TRUE )
```

```{r}
uni_pat_cli<-unique(data_clinical_patient$PATIENT_ID)
uni_pat_mut<-unique(data_mutations$Tumor_Sample_Barcode)
uni_pat_first12_mut<-substr(uni_pat_mut, start = 1, stop = 12)
pat_RNA<-colnames(RNA_data[2:554]) # get all the patient id
pat_RNA<-gsub("\\.", "-", pat_RNA) # change dot to dash
pat_first12_RNA<- substr(pat_RNA, start = 1, stop = 12) # only first 12 characters
unique_pat_rna<-unique(pat_first12_RNA) #find the unique patient in RNA dataset
unique_pat<-intersect(uni_pat_cli,uni_pat_first12_mut)
unique_pat<-intersect(unique_pat,unique_pat_rna)

index<-which(data_clinical_patient$PATIENT_ID %in% unique_pat)

#Filtering the Sex data
data_clinical_patient[which(data_clinical_patient$SEX == ""), "SEX"] = NA

#Filtering the Tumour Stage data
# remove any of the letters "a", "b" or "c", but only if they are at the end
# of the name, eg "stage iiia" would become simply "stage iii"
data_clinical_patient$AJCC_PATHOLOGIC_TUMOR_STAGE =  gsub("[ABC]$", "", data_clinical_patient$AJCC_PATHOLOGIC_TUMOR_STAGE)
# we remove those with stage "not reported", since they are unknown
data_clinical_patient[which(data_clinical_patient$AJCC_PATHOLOGIC_TUMOR_STAGE == ""), "AJCC_PATHOLOGIC_TUMOR_STAGE"] = NA
# finally, we also remove those with tumor stage 4, since they are too few
data_clinical_patient[which(data_clinical_patient$AJCC_PATHOLOGIC_TUMOR_STAGE == "STAGE IV"), "AJCC_PATHOLOGIC_TUMOR_STAGE"] = NA

#Filtering the Ethnicity data
data_clinical_patient[which(data_clinical_patient$ETHNICITY == ""), "ETHNICITY"] = NA

boxplot(data_clinical_patient$AGE[index])
barplot(table(data_clinical_patient$SEX[index]), main="Distribution of Sexes", xlab="Sex", ylab="Frequency", col="skyblue")
barplot(table(data_clinical_patient$AJCC_PATHOLOGIC_TUMOR_STAGE[index]), main="Distribution of Cancer Stages", xlab="Cancer Stages", ylab="Frequency", col="skyblue")
barplot(table(data_clinical_patient$ETHNICITY[index]), main="Distribution of Ethnicities", xlab="Ethnicity", ylab="Frequency", col="skyblue")
barplot(table(data_clinical_patient$OS_STATUS[index]), main="Distribution of Survival", xlab="Survival Status", ylab="Frequency", col="skyblue")

```
